version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: trustno1
      MYSQL_DATABASE: example
      MYSQL_USER: rob
      MYSQL_PASSWORD: makeitfunky
    ports:
    - 3306:3306
    volumes: 
    - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080